# PURPOSE: Read all blocks/*-retro.md files, extract token fields, produce governance/token-report.md
# INPUTS:  arch-root directory, blocks/*-retro.md files
# OUTPUTS: governance/token-report.md with per-block and per-phase token summary
# DEPS:    stdlib only (pathlib, re, dataclasses, argparse, datetime)
# SEE:     phases/phase-18.md block-113, sdk/health_report.py (output format reference)

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class TokenRecord:
    block_id: str
    phase: str
    tok_estimated: int | None
    tok_actual: int | None
    delta: int | None          # tok_actual - tok_estimated; None if either is missing
    date: str
    missing: bool              # True when tok_actual is absent or null

    @classmethod
    def from_retro(cls, path: Path) -> "TokenRecord | None":
        """Parse a retro file and return a TokenRecord. Returns None on fatal parse error."""
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return None

        block_id = _extract_field(text, r"^id:\s*(.+)")
        if not block_id:
            # Derive block_id from filename: block-NNN-*.md
            m = re.match(r"(block-\d+)", path.name)
            block_id = m.group(1) if m else path.stem

        phase = _extract_field(text, r"^phase:\s*(.+)") or "unknown"
        date_str = _extract_field(text, r"^created_at:\s*(.+)") or ""

        tok_estimated = _extract_int(text, r"^tok_estimated:\s*(.+)")
        tok_actual = _extract_int(text, r"^(?:tok_actual|tok-actual|tokens_actual):\s*(.+)")
        missing = tok_actual is None

        delta = None
        if tok_estimated is not None and tok_actual is not None:
            delta = tok_actual - tok_estimated

        return cls(
            block_id=block_id.strip(),
            phase=phase.strip(),
            tok_estimated=tok_estimated,
            tok_actual=tok_actual,
            delta=delta,
            date=date_str.strip(),
            missing=missing,
        )


def _extract_field(text: str, pattern: str) -> str | None:
    m = re.search(pattern, text, re.MULTILINE)
    if not m:
        return None
    return m.group(1).strip()


def _extract_int(text: str, pattern: str) -> int | None:
    """Extract an integer field; returns None for null/~/empty/non-numeric values."""
    val = _extract_field(text, pattern)
    if val is None:
        return None
    if val.lower() in ("null", "~", "none", ""):
        return None
    try:
        return int(val)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Tracker
# ---------------------------------------------------------------------------

class TokenTracker:
    def __init__(self, arch_root: Path) -> None:
        self.arch_root = arch_root
        self.records: list[TokenRecord] = []

    def load(self) -> "TokenTracker":
        """Scan all blocks/*-retro.md files and parse token records."""
        blocks_dir = self.arch_root / "blocks"
        if not blocks_dir.exists():
            return self
        retros = sorted(blocks_dir.glob("block-*-*.md"))
        retros = [r for r in retros if "LOG" not in r.name.upper()]
        for path in retros:
            rec = TokenRecord.from_retro(path)
            if rec is not None:
                self.records.append(rec)
        return self

    def report(self) -> str:
        """Generate markdown token report."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines: list[str] = [
            f"# Token Report — {now}",
            "",
            "Generated by `sdk/token_tracker.py`. Null tok_actual = field missing or not yet tracked.",
            "",
        ]

        # Per-block table
        lines += [
            "## Per-Block Summary",
            "",
            "| block_id | phase | tok_estimated | tok_actual | delta | date | missing |",
            "|----------|-------|--------------|------------|-------|------|---------|",
        ]
        for r in self.records:
            est = str(r.tok_estimated) if r.tok_estimated is not None else "—"
            act = str(r.tok_actual) if r.tok_actual is not None else "null"
            dlt = f"{r.delta:+d}" if r.delta is not None else "—"
            flag = "✗" if r.missing else "✓"
            lines.append(f"| {r.block_id} | {r.phase} | {est} | {act} | {dlt} | {r.date} | {flag} |")

        lines.append("")

        # Per-phase summary
        phases: dict[str, list[TokenRecord]] = {}
        for rec in self.records:
            phases.setdefault(rec.phase, []).append(rec)

        lines += [
            "## Per-Phase Summary",
            "",
            "| phase | blocks | tok_estimated_total | tok_actual_total | missing_count |",
            "|-------|--------|--------------------|--------------------|---------------|",
        ]
        for phase, recs in sorted(phases.items()):
            total_est = sum(r.tok_estimated for r in recs if r.tok_estimated is not None)
            total_act = sum(r.tok_actual for r in recs if r.tok_actual is not None)
            missing = sum(1 for r in recs if r.missing)
            est_str = str(total_est) if total_est > 0 else "—"
            act_str = str(total_act) if total_act > 0 else "—"
            lines.append(f"| {phase} | {len(recs)} | {est_str} | {act_str} | {missing} |")

        lines.append("")

        # Coverage stats
        total = len(self.records)
        tracked = sum(1 for r in self.records if not r.missing)
        pct = f"{tracked/total*100:.0f}%" if total > 0 else "n/a"
        lines += [
            "## Coverage",
            "",
            f"- Total blocks scanned: {total}",
            f"- Blocks with tok_actual: {tracked} ({pct})",
            f"- Blocks missing tok_actual: {total - tracked}",
            "",
            "_Advisory: blocks missing tok_actual were closed before Phase 18 enforcement or used --force._",
        ]

        return "\n".join(lines) + "\n"

    def write_report(self, out_dir: Path | None = None) -> Path:
        """Write the token report to governance/token-report.md."""
        out_dir = out_dir or (self.arch_root / "governance")
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / "token-report.md"
        out_path.write_text(self.report(), encoding="utf-8")
        return out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Generate governance/token-report.md from retro files")
    parser.add_argument("--arch-root", default=".", help="Path to cognitive-arch root")
    parser.add_argument("--dry-run", action="store_true", help="Print report to stdout; do not write file")
    parser.add_argument("--output-dir", default=None, help="Override output directory")
    args = parser.parse_args(argv)

    root = Path(args.arch_root).resolve()
    tracker = TokenTracker(root).load()
    report = tracker.report()

    if args.dry_run:
        print(report)
        return

    out_dir = Path(args.output_dir).resolve() if args.output_dir else None
    out_path = tracker.write_report(out_dir)
    print(f"[token_tracker] Report written: {out_path}")
    print(f"  {len(tracker.records)} blocks scanned, "
          f"{sum(1 for r in tracker.records if not r.missing)} with tok_actual")


if __name__ == "__main__":
    main()
