# sdk/integrity_check.py
# PURPOSE: Verify and regenerate SHA256 integrity lock for immutable-tagged files.
# INPUTS:  .integrity.lock (lock file), arch root directory
# OUTPUTS: verification report to stdout; updated .integrity.lock on regenerate
# DEPS:    stdlib only (hashlib, pathlib, re, argparse, sys)
# SEE:     commands/integrity-bump.md, protocols/architecture-integrity.md, audit.sh check 10

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


LOCK_FILE = ".integrity.lock"
PROTECTION_FIELD = "protection: immutable"

# A file is immutable ONLY when `protection: immutable` appears as a YAML
# frontmatter field (a line inside the leading ---...--- block), NOT when the
# phrase is merely discussed in prose (manifests, phase docs, retros). Matching
# the field line, optionally quoted (protection: "immutable" / 'immutable'),
# with trailing whitespace/comment tolerated.
_FRONTMATTER_PROTECTION_RE = re.compile(
    r"^\s*protection:\s*['\"]?immutable['\"]?\s*(?:#.*)?$",
    re.MULTILINE,
)


def sha256_of_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _frontmatter_block(text: str) -> str:
    """Return the YAML frontmatter (between the leading '---' and the next '---').

    Frontmatter must START the file: the first non-empty line is the opening
    '---' fence. Returns '' when there is no leading fenced block, so a prose
    mention of '---' or 'protection: immutable' deeper in the document is never
    treated as frontmatter.
    """
    # Tolerate a UTF-8 BOM and leading blank lines before the opening fence.
    stripped = text.lstrip("﻿")
    lead = stripped.lstrip("\r\n")
    if not lead.startswith("---"):
        return ""
    # First line must be exactly a '---' fence (allow trailing whitespace).
    nl = lead.find("\n")
    if nl == -1:
        return ""
    first = lead[:nl].rstrip()
    if first != "---":
        return ""
    rest = lead[nl + 1:]
    # Closing fence: a line that is exactly '---' (allow trailing whitespace).
    m = re.search(r"^---\s*$", rest, re.MULTILINE)
    if not m:
        return ""
    return rest[:m.start()]


def is_immutable_text(text: str) -> bool:
    """True iff the document declares `protection: immutable` in its frontmatter."""
    return bool(_FRONTMATTER_PROTECTION_RE.search(_frontmatter_block(text)))


def load_lock(arch_root: Path) -> dict[str, str]:
    """Return {relative_path: expected_hash} from .integrity.lock."""
    lock_path = arch_root / LOCK_FILE
    if not lock_path.exists():
        return {}
    entries: dict[str, str] = {}
    for line in lock_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Format: relative/path  sha256:HEXHASH
        m = re.match(r"^(\S+)\s+sha256:([0-9a-f]{64})$", line)
        if m:
            entries[m.group(1)] = m.group(2)
    return entries


def find_immutable_files(arch_root: Path) -> list[str]:
    """Return list of relative POSIX paths for files tagged protection:immutable."""
    immutable: list[str] = []
    for md_file in arch_root.rglob("*.md"):
        # Skip files in hidden dirs and manifests/_archive
        rel = md_file.relative_to(arch_root).as_posix()
        if any(part.startswith(".") for part in rel.split("/")):
            continue
        try:
            text = md_file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        # Frontmatter field only — a prose mention of the phrase does NOT count.
        if is_immutable_text(text):
            immutable.append(rel)
    return sorted(immutable)


def verify(arch_root: Path) -> list[tuple[str, str]]:
    """
    Check all locked files against current hashes.
    Returns list of (path, status) where status is 'OK', 'MISMATCH', or 'MISSING'.
    """
    lock = load_lock(arch_root)
    if not lock:
        return [("(no lock file)", "MISSING")]

    results: list[tuple[str, str]] = []
    for rel_path, expected_hash in lock.items():
        full_path = arch_root / rel_path
        if not full_path.exists():
            results.append((rel_path, "MISSING"))
        else:
            actual = sha256_of_file(full_path)
            results.append((rel_path, "OK" if actual == expected_hash else "MISMATCH"))
    return results


def regenerate(arch_root: Path) -> dict[str, str]:
    """Recompute hashes for all immutable-tagged files and write new .integrity.lock."""
    files = find_immutable_files(arch_root)
    entries: dict[str, str] = {}
    for rel in files:
        h = sha256_of_file(arch_root / rel)
        entries[rel] = h

    lock_path = arch_root / LOCK_FILE
    lines = [
        "# .integrity.lock — SHA256 hashes of immutable-tagged files",
        f"# Regenerated by: sdk/integrity_check.py --regenerate",
        "# See: commands/integrity-bump.md for the approved human-approval workflow",
        "",
    ]
    for rel, h in entries.items():
        lines.append(f"{rel}  sha256:{h}")
    lines.append("")
    lock_path.write_text("\n".join(lines), encoding="utf-8")
    return entries


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Integrity lock verification for cognitive-arch")
    parser.add_argument("--arch-root", default=".", help="Root of the cognitive-arch directory")
    parser.add_argument("--verify", action="store_true", help="Verify current files against lock")
    parser.add_argument("--regenerate", action="store_true", help="Regenerate .integrity.lock")
    parser.add_argument("--strict", action="store_true", help="Exit 1 on any mismatch (for CI)")
    args = parser.parse_args()

    arch_root = Path(args.arch_root).resolve()

    if args.regenerate:
        entries = regenerate(arch_root)
        print(f"Regenerated .integrity.lock with {len(entries)} entries.")
        sys.exit(0)

    results = verify(arch_root)
    has_mismatch = any(s != "OK" for _, s in results)

    for path, status in results:
        prefix = "OK:   " if status == "OK" else "ERROR:"
        print(f"{prefix} {path}: {status}")

    if has_mismatch:
        print("\nRun `python sdk/integrity_check.py --regenerate` ONLY after human review.")
        print("See: commands/integrity-bump.md")
        sys.exit(1)
    else:
        print(f"All {len(results)} immutable files verified OK.")
