# PURPOSE: Re-validate the five Group-S security axioms (S1-S5); refresh security-status.md.
# INPUTS:  arch-root, PROTOCOLS.md (S1-S5), design/ + governance/ (threat models),
#          manifests/ + blocks/ (security:true manifests)
# OUTPUTS: governance/security-status.md
# DEPS:    stdlib only (argparse, datetime, re, pathlib)
# SEE:     commands/security-review.md, protocols/threat-model-generation.md

"""
Security Review Revalidation for cognitive-arch projects.

Re-runs a STRUCTURAL validation of the five Group-S security axioms (S1-S5)
parsed from PROTOCOLS.md and checks the supporting artifacts: threat models in
design/ (axiom S4) and security:true manifests + their review gates (axiom S5).
Writes a dated status to governance/security-status.md and prints a one-line
verdict. Required every 30 days (registry id: security-revalidation).

This is a policy + artifact-presence revalidation, NOT a code scanner. Deep
per-block review happens at block close via commands/security-review.md (S5).

Usage:
  python sdk/security_review.py --arch-root . --revalidate
  python sdk/security_review.py --arch-root . --dry-run
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date, datetime, timezone, timedelta
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # Windows cp1252-safe output

REVALIDATION_INTERVAL_DAYS = 30


def _read(arch_root: Path, rel: str, default: str = "") -> str:
    p = arch_root / rel
    if not p.exists():
        return default
    try:
        return p.read_text(encoding="utf-8")
    except OSError:
        return default


def _parse_axioms(protocols: str) -> dict:
    """Find S1..S5 axiom titles from PROTOCOLS.md (format: **S1: Title.** ...)."""
    found: dict = {}
    for m in re.finditer(r"\*\*(S[1-5]):\s*([^*]+?)\.\*\*", protocols):
        found[m.group(1)] = m.group(2).strip()
    # Looser fallback: a bare "S1:" reference counts as present.
    for n in range(1, 6):
        key = f"S{n}"
        if key not in found and re.search(rf"\b{key}:", protocols):
            found[key] = "(present)"
    return found


def _threat_models(arch_root: Path) -> list[str]:
    hits = []
    for d in ("design", "governance"):
        dd = arch_root / d
        if dd.exists():
            for f in dd.rglob("*.md"):
                if "threat" in f.stem.lower():
                    hits.append(str(f.relative_to(arch_root)).replace("\\", "/"))
    return hits


def _security_manifests(arch_root: Path) -> list[str]:
    hits = []
    for d in ("manifests", "blocks"):
        dd = arch_root / d
        if dd.exists():
            for f in dd.glob("*.md"):
                try:
                    txt = f.read_text(encoding="utf-8")
                except OSError:
                    continue
                if re.search(r"^security:\s*true", txt, re.IGNORECASE | re.MULTILINE):
                    hits.append(f.name)
    return hits


def revalidate(arch_root: Path) -> tuple[str, str]:
    today = date.today().isoformat()
    next_due = (date.today() + timedelta(days=REVALIDATION_INTERVAL_DAYS)).isoformat()
    axioms = _parse_axioms(_read(arch_root, "PROTOCOLS.md"))
    threats = _threat_models(arch_root)
    sec_manifests = _security_manifests(arch_root)

    rows = []
    missing_axiom = False
    for n in range(1, 6):
        key = f"S{n}"
        title = axioms.get(key)
        if title is None:
            status, detail = "MISSING", "axiom not found in PROTOCOLS.md"
            missing_axiom = True
        elif key == "S4":
            if threats:
                status, detail = "OK", f"{len(threats)} threat model(s): {', '.join(threats[:3])}"
            elif sec_manifests:
                status, detail = "WARN", "security-critical work exists but no threat model in design/"
            else:
                status, detail = "OK", "no security-critical code yet"
        elif key == "S5":
            if sec_manifests:
                status, detail = "REVIEW", f"{len(sec_manifests)} security:true manifest(s) — confirm each had a gate"
            else:
                status, detail = "OK", "no security:true manifests yet"
        else:
            status = "OK"
            detail = title if title != "(present)" else "axiom present in PROTOCOLS.md"
        rows.append(f"| {key} | {status} | {detail} |")

    verdict = "DEGRADED" if missing_axiom else "PASS"
    manifest_list = (" — " + ", ".join(sec_manifests[:8])) if sec_manifests else ""
    report = f"""# Security Status — {today}

Generated by: sdk/security_review.py --revalidate
Architecture root: {arch_root.resolve()}

**Verdict: {verdict}**  |  Next revalidation due: **{next_due}** (every {REVALIDATION_INTERVAL_DAYS} days)

## S1-S5 axiom revalidation

| Axiom | Status | Detail |
|-------|--------|--------|
{chr(10).join(rows)}

## Supporting artifacts

- Threat models (design/, governance/): {len(threats)}
- security:true manifests: {len(sec_manifests)}{manifest_list}

*Structural revalidation only (policy + artifact presence). Deep per-block code
review runs at block close via commands/security-review.md (axiom S5).
Generated {datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")}.*
"""
    return report, verdict


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="security_review",
        description="Revalidate the S1-S5 Group-S security axioms (30-day cadence).",
    )
    p.add_argument("--arch-root", metavar="PATH", default=".",
                   help="Path to the cognitive-arch root (default: current directory).")
    p.add_argument("--revalidate", action="store_true",
                   help="Run the 30-day S1-S5 revalidation and refresh security-status.md.")
    p.add_argument("--dry-run", action="store_true",
                   help="Validate inputs are readable and output is writable. No file written.")
    p.add_argument("--output-dir", metavar="PATH", default="governance",
                   help="Directory to write security-status.md to (default: governance/).")
    return p


def main() -> None:
    args = build_parser().parse_args()
    arch_root = Path(args.arch_root).resolve()
    if not arch_root.exists():
        print(f"ERROR: arch-root not found: {arch_root}", file=sys.stderr)
        sys.exit(1)
    out_dir = arch_root / args.output_dir
    if args.dry_run:
        try:
            out_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            print(f"ERROR: cannot create output dir {out_dir}: {exc}", file=sys.stderr)
            sys.exit(1)
        print("Security review dry-run passed.")
        sys.exit(0)
    report, verdict = revalidate(arch_root)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "security-status.md"
    out_path.write_text(report, encoding="utf-8")
    # Exit 0 on a successful run regardless of verdict — the verdict lives in the
    # report so the scheduler records the tool as "ran" and refreshes last_run.
    print(f"Security status written to: {out_path} — verdict: {verdict}")
    sys.exit(0)


if __name__ == "__main__":
    main()
